"""Frozen numerical controls; never imported by the production benchmark."""
from pathlib import Path
from tone_mapper import ROOT
from tools.profiling.android.quality_sweep import Candidate

VARIANTS = {'guided-fused-reconstruction': {'half_aux': True,
                                 'compute_srgb': True,
                                 'cached_baseline': True,
                                 'log_exposure': True,
                                 'separable_guided': True,
                                 'precomputed_ev': True,
                                 'residual_pyramid': True,
                                 'gather_reduction': True,
                                 'guided_vertical': 2,
                                 'guided_threads_y': 16,
                                 'guided_static_windows': True,
                                 'guided_batch': 2,
                                 'guided_direct_moments': True,
                                 'direct_batch': 1,
                                 'tail_fusion': True,
                                 'tail_max_width': 16,
                                 'tail_max_height': 8,
                                 'tail_x': 16,
                                 'fused_fine_reconstruction': True,
                                 'half_guide': True,
                                 'half_compact': True,
                                 'half_row_coefficients': True,
                                 'reuse_moment_storage': True,
                                 'guided_gather_rows': True,
                                 'direct_residual_weights': True,
                                 'gather_x': 4,
                                 'gather_y': 8},
 'guided-pyramid-layout': {'half_aux': True,
                           'compute_srgb': True,
                           'cached_baseline': True,
                           'log_exposure': True,
                           'separable_guided': True,
                           'precomputed_ev': True,
                           'residual_pyramid': True,
                           'gather_reduction': True,
                           'guided_vertical': 2,
                           'guided_threads_y': 16,
                           'guided_static_windows': True,
                           'guided_batch': 2,
                           'guided_direct_moments': True,
                           'direct_batch': 1,
                           'tail_fusion': True,
                           'tail_max_width': 16,
                           'tail_max_height': 8,
                           'tail_x': 16,
                           'fused_fine_reconstruction': True,
                           'half_guide': True,
                           'half_compact': True,
                           'half_row_coefficients': True,
                           'reuse_moment_storage': True,
                           'guided_gather_rows': True,
                           'direct_residual_weights': True,
                           'gather_x': 4,
                           'gather_y': 8,
                           'residual_float_from': 3,
                           'compact_tail_storage': True,
                           'tail_grid_walk': True,
                           'skip_tail_clear': True,
                           'fuse_tail_base': True,
                           'curve_log': True,
                           'gather_quad_log': True,
                           'guided_interior_fit': True,
                           'shared_input_log': True,
                           'pyramid_x': 4,
                           'pyramid_y': 16},
 'guided-unsigned-gather': {'half_aux': True,
                            'compute_srgb': True,
                            'cached_baseline': True,
                            'log_exposure': True,
                            'separable_guided': True,
                            'precomputed_ev': True,
                            'residual_pyramid': True,
                            'gather_reduction': True,
                            'guided_vertical': 2,
                            'guided_threads_y': 16,
                            'guided_static_windows': True,
                            'guided_batch': 2,
                            'guided_direct_moments': True,
                            'direct_batch': 1,
                            'tail_fusion': True,
                            'tail_max_width': 16,
                            'tail_max_height': 8,
                            'tail_x': 16,
                            'fused_fine_reconstruction': True,
                            'half_guide': True,
                            'half_compact': True,
                            'half_row_coefficients': True,
                            'reuse_moment_storage': True,
                            'guided_gather_rows': True,
                            'direct_residual_weights': True,
                            'gather_x': 4,
                            'gather_y': 8,
                            'residual_float_from': 3,
                            'compact_tail_storage': True,
                            'tail_grid_walk': True,
                            'skip_tail_clear': True,
                            'fuse_tail_base': True,
                            'curve_log': True,
                            'gather_quad_log': True,
                            'guided_interior_fit': True,
                            'shared_input_log': True,
                            'pyramid_x': 4,
                            'pyramid_y': 16,
                            'gather_unsigned_source': True}}

VARIANTS.update({'guided-packed-coefficients': {'half_aux': True,
                                'compute_srgb': True,
                                'cached_baseline': True,
                                'log_exposure': True,
                                'separable_guided': True,
                                'precomputed_ev': True,
                                'residual_pyramid': True,
                                'gather_reduction': True,
                                'guided_vertical': 2,
                                'guided_threads_y': 16,
                                'guided_static_windows': True,
                                'guided_batch': 2,
                                'guided_direct_moments': True,
                                'direct_batch': 1,
                                'tail_fusion': True,
                                'tail_max_width': 16,
                                'tail_max_height': 8,
                                'tail_x': 16,
                                'fused_fine_reconstruction': True,
                                'half_guide': True,
                                'half_compact': True,
                                'half_row_coefficients': True,
                                'reuse_moment_storage': True,
                                'guided_gather_rows': True,
                                'direct_residual_weights': True,
                                'gather_x': 4,
                                'gather_y': 8,
                                'residual_float_from': 3,
                                'compact_tail_storage': True,
                                'tail_grid_walk': True,
                                'skip_tail_clear': True,
                                'fuse_tail_base': True,
                                'curve_log': True,
                                'gather_quad_log': True,
                                'guided_interior_fit': True,
                                'shared_input_log': True,
                                'pyramid_x': 4,
                                'pyramid_y': 16,
                                'gather_unsigned_source': True,
                                'coefficient_padding': 4,
                                'packed_half_coefficients': True},
 'guided-coefficient-layout': {'half_aux': True,
                               'compute_srgb': True,
                               'cached_baseline': True,
                               'log_exposure': True,
                               'separable_guided': True,
                               'precomputed_ev': True,
                               'residual_pyramid': True,
                               'gather_reduction': True,
                               'guided_vertical': 2,
                               'guided_threads_y': 16,
                               'guided_static_windows': True,
                               'guided_batch': 2,
                               'guided_direct_moments': True,
                               'direct_batch': 1,
                               'tail_fusion': True,
                               'tail_max_width': 16,
                               'tail_max_height': 8,
                               'tail_x': 16,
                               'fused_fine_reconstruction': True,
                               'half_guide': True,
                               'half_compact': True,
                               'half_row_coefficients': True,
                               'reuse_moment_storage': True,
                               'guided_gather_rows': True,
                               'direct_residual_weights': True,
                               'gather_x': 4,
                               'gather_y': 8,
                               'residual_float_from': 3,
                               'compact_tail_storage': True,
                               'tail_grid_walk': True,
                               'skip_tail_clear': True,
                               'fuse_tail_base': True,
                               'curve_log': True,
                               'gather_quad_log': True,
                               'guided_interior_fit': True,
                               'shared_input_log': True,
                               'pyramid_x': 4,
                               'pyramid_y': 16,
                               'gather_unsigned_source': True,
                               'coefficient_padding': 4}})

class ReferenceCandidate(Candidate):
    def __init__(self,device,mapper,variant):
        self.device,self.mapper,self.config=device,mapper,dict(VARIANTS[variant])
        if self.config.get('residual_snorm'):
            # Every lightness lies in [0,max_lightness]; normalized differences
            # and their Gaussian averages therefore remain representable in SNORM.
            self.config['residual_scale'] = 1.0 / max(1.0, mapper.curve.max_lightness)
        mapping={'PACKED_HALF_COEFFICIENTS':('packed_half_coefficients',False),'COEFF_PAD':('coefficient_padding',0),'GUIDED_INTERIOR_FIT':('guided_interior_fit',False),'SHARED_INPUT_LOG':('shared_input_log',False),'GATHER_QUAD_LOG':('gather_quad_log',False),'FUSE_TAIL_BASE':('fuse_tail_base',False),'SKIP_TAIL_CLEAR':('skip_tail_clear',False),'COMPACT_TAIL_STORAGE':('compact_tail_storage',False),'TAIL_GRID_WALK':('tail_grid_walk',False),'FLOAT_TAIL_WEIGHTS':('float_tail_weights',False),'FLOAT_TAIL_RESIDUAL':('float_tail_residual',False),'COMPENSATE_RESIDUAL':('compensate_residual',False),'DIRECT_RESIDUAL_WEIGHTS':('direct_residual_weights',False),'GUIDED_GATHER_ROWS':('guided_gather_rows',False),'REUSE_MOMENT_STORAGE':('reuse_moment_storage',False),'HALF_ROW_COEFFICIENTS':('half_row_coefficients',False),'DIRECT_BATCH':('direct_batch',2),'TAIL_X':('tail_x',8),'GUIDED_DIRECT_MOMENTS':('guided_direct_moments',False),'GUIDED_STATIC_WINDOWS':('guided_static_windows',False),'GUIDED_VERTICAL':('guided_vertical',1),'GUIDED_THREADS_Y':('guided_threads_y',self.config.get('tile_y',16)),'GUIDED_BATCH':('guided_batch',1),'GUIDED_SLIDING':('guided_sliding',False),'WAVE_REDUCTION':('wave_reduction',False),'SHARED_PADDING':('shared_padding',0),'HALF_MOMENT_PRODUCTS':('half_moment_products',False),'GATHER_X':('gather_x',8),'GATHER_Y':('gather_y',8),'HALF_GATHER':('half_gather',False),'SCALAR_REDUCTION':('scalar_reduction',False),'LOG_PRODUCT':('log_product',False),'MOMENT_INPUT':('moment_input',False),'PACKED_RESIDUAL':('packed_residual',False),'RESIDUAL_PYRAMID':('residual_pyramid',False),'CURVE_LOG':('curve_log',False),'PRECOMPUTED_EV':('precomputed_ev',False),'SINGLE_WEIGHT':('single_weight',False),'REUSE_SHARED':('reuse_shared',False),'REDUCTION_LOAD':('reduction_load',False),'REDUCTION_GRID':('reduction_grid',4),'GUIDED_RADIUS':('guided_radius',2),'CACHED_BASELINE':('cached_baseline',False),'LOG_EXPOSURE':('log_exposure',False),'TILE_X':('tile_x',16),'TILE_Y':('tile_y',16),'WORK_X':('work_x',8),'WORK_Y':('work_y',8),'SEPARABLE_GUIDED':('separable_guided',False)}
        mapping.update(PYRAMID_X=('pyramid_x',self.config.get('work_x',8)),
                       PYRAMID_Y=('pyramid_y',self.config.get('work_y',8)))
        defines={key:str(int(self.config.get(name,default))) for key,(name,default) in mapping.items()}
        defines['RESIDUAL_SCALE']=str(self.config.get('residual_scale',1.0))
        defines['PACKED_WEIGHT_BIAS']=str(self.config.get('packed_weight_bias',0.0))
        session=device.create_slang_session(compiler_options={'include_paths':[ROOT/'shaders'],'defines':defines})
        self.kernels={name:device.create_compute_kernel(session.load_program(str(ROOT/'tests/fixtures/fusion_compact_reference.slang'),[name])) for name in ['reconstruct_ev_fused','reduce_setup_gather','guided_moments','reduce_horizontal','reduce_setup_vertical','reduce_setup_cooperative','tail_reconstruct','reconstruct_ev','reduce_setup','downsample_compact','reconstruct_compact','reconstruct_guided']}
        self.unsigned_gather = None
        if self.config.get('gather_unsigned_source'):
            unsigned_session = device.create_slang_session(compiler_options={
                'include_paths': [ROOT/'shaders'],
                'defines': {**defines, 'GATHER_UNSIGNED_SOURCE': '1'}})
            self.unsigned_gather = device.create_compute_kernel(unsigned_session.load_program(
                str(ROOT/'tests/fixtures/fusion_compact_reference.slang'), ['reduce_setup_gather']))
        self.final=device.create_compute_kernel(session.load_program(str(Path(__file__).with_name('joint.slang')) if self.config.get('joint_upsample') else 'guided.slang',['apply_joint_linear' if self.config.get('joint_upsample') else 'apply_exposure_production']))
